' Preview durch <Alt>d

@startuml ER Diagramm

' hide the spot
hide circle

' Kraehenfuesse vermeiden
skinparam linetype ortho

entity "kunde" {
    id : integer <<generated>>
  --
  * nachname : text
  * email : text <<unique>>
    version: integer <<default 0>>
    erzeugt: timestamp
    aktualisiert: timestamp
}

entity "adresse" {
  * id : integer <<generated>>
  --
  * strasse : text
  * hausnummer : text
  * plz : text
  * ort : text
  * **kunde_id**: integer <<FK>>
}

entity "bestellung" {
  * id : integer <<generated>>
  --
  * produktname : text
  * menge : integer
  * **kunde_id**: integer <<FK>>
}

kunde ||.right.|| adresse
kunde ||..o{ bestellung

footer Leon Jungkind

@enduml
