' Preview durch <Alt>d

@startuml Komponenten

left to right direction

actor RESTClient
actor GraphQLClient

node "kunde" {
  [kunde_read_router]
  [kunde_write_router]

  [graphql_schema\n(Query / Mutation)]

  [kunde_read_service]
  [kunde_write_service]

  [kunde_repository]
}

cloud {
    [SQLAlchemy]
}

database "DB kunde" {
    [Tabelle kunde]
    [Tabelle adresse]
    [Tabelle bestellung]
}

RESTClient ~~> [kunde_read_router]
RESTClient ~~> [kunde_write_router]
GraphQLClient ~~> [graphql_schema\n(Query / Mutation)]

[kunde_read_router] ..> [kunde_read_service]
[kunde_write_router] ..> [kunde_write_service]
[graphql_schema\n(Query / Mutation)] ..> [kunde_read_service]
[graphql_schema\n(Query / Mutation)] ..> [kunde_write_service]
[kunde_read_service] ..> [kunde_repository]
[kunde_write_service] ..> [kunde_repository]

[kunde_repository] ~~> [SQLAlchemy]
[SQLAlchemy] ~~> [Tabelle kunde]
[SQLAlchemy] ~~> [Tabelle adresse]
[SQLAlchemy] ~~> [Tabelle bestellung]

footer Leon Jungkind

@enduml
