' Preview durch <Alt>d

@startuml Schichtenarchitektur

package kunde #DDDDDD {
    package router #FFFFFF {
        [@router.get()\nget_by_id()\n\n@router.get()\nget()\n\n@router.get()\nget_nachnamen()] as kundeReadRouter
        [@router.post()\npost()\n\n@router.put()\nput()\n\n@router.delete()\ndelete_by_id()] as kundeWriteRouter

        [kundeReadRouter] -right[hidden]-> [kundeWriteRouter]
    }

    package service #FFFFFF {
        [find_by_id()\nfind()\nfind_nachnamen()] as kundeReadService
        [create()\nupdate()\ndelete_by_id()] as kundeWriteService
    }

    [kundeReadRouter] --> [kundeReadService]
    [kundeWriteRouter] --> [kundeWriteService]

    package repository #FFFFFF {
        [find_by_id()\nfind()\nexists_email()\nfind_nachnamen()\ncreate()\nupdate()\ndelete_by_id()] as kundeRepository
    }

    [kundeReadService] --> [kundeRepository]
    [kundeWriteService] --> [kundeRepository]

    package entity #FFFFFF {
        [Kunde]
        [Adresse]
        [Bestellung]

        [Kunde] -right[hidden]-> [Adresse]
        [Adresse] -down[hidden]-> [Bestellung]
    }

    [kundeReadRouter] ..> [Kunde]
    [kundeWriteRouter] ..> [Kunde]
    [kundeReadService] .left.> [Kunde]
    [kundeWriteService] ..> [Kunde]
    [kundeRepository] ..> [Kunde]
}

RESTClient ~~> [kundeReadRouter]
RESTClient ~~> [kundeWriteRouter]

cloud {
    [SQLAlchemy\n(OR-Mapping)] as SQLAlchemy
}

[kundeRepository] ~down~> [SQLAlchemy]
entity ~~> [SQLAlchemy]

database "DB kunde" as db {
    [Tabelle kunde]
    [Tabelle adresse]
    [Tabelle bestellung]
}

[SQLAlchemy] ~down~> db

footer Leon Jungkind

@enduml
