' Preview durch <Alt>d

@startuml Use Cases

actor Admin
actor Kunde

rectangle kunde {
    Admin --> (Kunde anlegen)
    Admin --> (Kunde suchen)
    Admin --> (Kunde aendern)
    Admin --> (Kunde loeschen)
    Kunde --> (Kunde suchen)
}

footer Leon Jungkind

@enduml
